# Generated by Django 2.1.1 on 2018-09-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('emailid', models.EmailField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
